common gridstorage, allgrids
common fields, list_str, mass_per_particle, divide_by_density, $
  var_index,  center, slice_value, xy_sl_size,  slice_size, slice_ori, $
  grid_info, data_dir, sds_num, smoothing, interpolate_i
common images, image_stack, N_images, snap_counter, x_stuetz, y_stuetz, z_stuetz,dx_stuetz,n_stuetz
common options, verbose
common widgets,  draw_area, draw_cm, TOP_BASE, base2, base3, slice_val_w, slice_text, $
  ISO_BASE, wISO, wSLICER, IS_VAL, peak_ids, peak_opt, snap_base, mi_ma_base_id
common custom, z_current
common peak_stuff, peaks, N_peaks, max_peak_nr, current_peak_file, current_peak
common vel_stuff, vel, vel_one, vel_two, cons_vel, substracting_vel
common ISO, verteces, polys, is_value, cube_dim, threeD_smoothing,shade_state
common packAMR, amr_is_packed
